"""empty message

Revision ID: 208359186f29
Revises: 
Create Date: 2025-07-09 09:54:28.478481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208359186f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('roles',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('manager', 'developer', 'admin', name='roles_enum'),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('role_roles_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('role_roles_key'), ['roles'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('roles',
               existing_type=sa.Enum('manager', 'developer', 'admin', name='roles_enum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
